### PR TITLE
Add ICMP requirement

### PR DESCRIPTION
**Pull request by mkowalski**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)

### CODE REVIEW

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FR4NK-W — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @mkowalski)

___
*[content/faq/join_infrastructure.md, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130#-LvM-HF-2S_mHyV9XgsT:-LvM-HF-2S_mHyV9XgsU:bcihsjw) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/e4c8b4a95b94ae7346a25e5145080ed247829d52/content/faq/join_infrastructure.md#L65)):*
> ```Markdown
> 
> {% include alert type="note" content="
> In case of stateful firewalls in the network, all the rules can be changed into a simple "ALLOW ESTABLISHED" rule in order to facilitate the management of the rulesets.
> ```

Bit vague, no?
I guess we want "ALLOW ESTABLISHED" for incoming

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[content/faq/join_infrastructure.md, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130#-LvM-HF-2S_mHyV9XgsT:-LvM04Ue-GUvPOMsbHar:b-q6hx9b) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/e4c8b4a95b94ae7346a25e5145080ed247829d52/content/faq/join_infrastructure.md#L65)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Bit vague, no?
I guess we want "ALLOW ESTABLISHED" for incoming
</blockquote></details>

How about now? Just moved it "unconditionally" to the incoming

**Review by FR4NK-W — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @mkowalski)

___
*[content/faq/join_infrastructure.md, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130#-LvM-HF-2S_mHyV9XgsT:-LvM0RSPDKRUJJQnd5QG:b5ron3z) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/e4c8b4a95b94ae7346a25e5145080ed247829d52/content/faq/join_infrastructure.md#L65)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

How about now? Just moved it "unconditionally" to the incoming
</blockquote></details>

I think we only really need it for :80 and :443 for package installation and so on, but yes that works

**Review by FR4NK-W — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130#-:-LvM0e1b4-3dHcZ4VK-d:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @mkowalski)

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: all files reviewed, 1 unresolved discussion (waiting on @mkowalski)

**Review by mkowalski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[content/faq/join_infrastructure.md, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130#-LvM-HF-2S_mHyV9XgsT:-LvM1KfHEWf93ClEN4wt:b-mxdosw) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/e4c8b4a95b94ae7346a25e5145080ed247829d52/content/faq/join_infrastructure.md#L65)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

I think we only really need it for :80 and :443 for package installation and so on, but yes that works
</blockquote></details>

And outgoing 123 for NTP, and 53 for DNS at least

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FR4NK-W — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/130#-:-LvPMktD85lpvBQimVlU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
