### PR TITLE
Tutorial on setting up SIGs on SCIONLab user ASes

### PR DESCRIPTION
**Pull request by FR4NK-W**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84)

### CODE REVIEW

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-:-LZ4wz2941SRAiP0kegZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonghoonkwon)

**Review by jonghoonkwon — CHANGES_REQUESTED** [review]
I think this tutorial needs to be more simplified. For example, the configuration of the two SIGs is almost identical except for the IP address and AS number. I'd therefore suggest to explain the configuration once using parameters such as `IP A` and `AS A`, rather than describing twice for each configuration step with detailed variables.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-:-LZ5L6YSAgK7ohGubMUT:b-8v9ps0)* status: all files reviewed, 5 unresolved discussions (waiting on @FR4NK-W)

___
*[content/sample_projects/remote_sig.md, line 10 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5E2mG076Fof9T9izr:-LZ5E2mG076Fof9T9izs:b-ib90u7) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L10)):*
> ```Markdown
> To test the SIG we will make use of the Vagrant configurations provided on [scionlab.org](https://scionlab.org/#/login).
> Login to your account and use the button `Generate a new SCIONLab AS`.
> Download the configuration and unpack it to your test directory.
> ```

Initiating SCIONLab VM is already described in `How to run SCION VM` section.
Simply initiating two SCIONLab ASes, namely AS A and B, would be sufficient for the environment description.
___
*[content/sample_projects/remote_sig.md, line 59 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5Ivur9B92h4oif6hb:-LZ5GZ5Z2PLeT6-hK5Ys:bpxng5g) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L59)):*
> ```Markdown
> Create the configuration for the sigA at ${SC}/gen/ISD${ISD}/AS${AS}/sig${IA}-1/sigA.config:
> 
> (You need to replace ${AS}, ${IA} and ${IAd} with the actual values on your system in these configuration files.)
> ```

A lack of explanation for ${AS}, ${IA}, and ${IAd}. Give some correct examples for the variables. 
___
*[content/sample_projects/remote_sig.md, line 73 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5HyeUCmYBHktgMPX7:-LZ5HyeUCmYBHktgMPX8:bumxmbh) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L73)):*
> ```Markdown
> 
>   # The bind IP address (required)
>   IP = "10.0.8.A"
> ```

Add a comment that user needs to put the IP address down here. 
___
*[content/sample_projects/remote_sig.md, line 310 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5Kl4xD_oVVNqnvHO8:-LZ5Kl4xD_oVVNqnvHO9:b-jppfwt) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L310)):*
> ```Markdown
> echo "Hello World!" > $SC/WWW/hello.html
> cd $SC/WWW/ && python3 -m http.server --bind 172.16.12.1 8081 &
> ```
> ```

Move this http server configuration to the following `Testing` section with a simple description about `testing example`
___
*[content/sample_projects/remote_sig.md, line 318 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5KQPS4DlA-UQxFIoW:-LZ5KQPS4DlA-UQxFIoX:b4w0x11) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L318)):*
> ```Markdown
> ```
> ```

Add a subtitle ` Testing`

**Review by FR4NK-W — COMMENTED** [review]
@jonghoonkwon  Thank you for your suggestions for simplification.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-:-LZKDa3fC8X_XwQS_g_t:b-y9wpwc)* status: 32 of 37 files reviewed, 5 unresolved discussions (waiting on @FR4NK-W, @jonghoonkwon, and @juagargi)

___
*[content/sample_projects/remote_sig.md, line 10 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5E2mG076Fof9T9izr:-LZKCAok1huLC-i1FS_O:b-2cw4w9) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L10)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Initiating SCIONLab VM is already described in `How to run SCION VM` section.
Simply initiating two SCIONLab ASes, namely AS A and B, would be sufficient for the environment description.
</blockquote></details>

Agreed, I'll remove that section
___
*[content/sample_projects/remote_sig.md, line 59 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5Ivur9B92h4oif6hb:-LZKCK-p49RtwX5hUqKW:b-c8ha0v) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L59)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

A lack of explanation for ${AS}, ${IA}, and ${IAd}. Give some correct examples for the variables. 
</blockquote></details>

Those variables are set in the previous step
___
*[content/sample_projects/remote_sig.md, line 73 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5HyeUCmYBHktgMPX7:-LZKChxcAKsMPt2ZhOga:bwzrn7i) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L73)):*
> Add a comment that user needs to put the IP address down here.


The command is given bellow:

>sed -i "s/10.0.8.A/${tunIP}/g" ${SC}/gen/ISD${ISD}/AS${AS}/sig${IA}-1/sigA.config
___
*[content/sample_projects/remote_sig.md, line 310 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5Kl4xD_oVVNqnvHO8:-LZKCvd8BmLZIRadr-jU:b-wo63cu) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L310)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Move this http server configuration to the following `Testing` section with a simple description about `testing example`
</blockquote></details>

Good suggestion

**Review by jonghoonkwon — COMMENTED** [review]
:lgtm: :thumbsup: 

> Reviewed 36 of 37 files at r1, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-:-LZKGruD1ATRepq5BnK1:b-wpm7nb)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84)* status: all files reviewed, 1 unresolved discussion (waiting on @jonghoonkwon)

___
*[content/sample_projects/remote_sig.md, line 318 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84#-LZ5KQPS4DlA-UQxFIoW:-LZKciIm2JugA0tVq6e6:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/7b9193345904dd965b4aa8e6d1ce0d568e933a89/content/sample_projects/remote_sig.md#L318)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Add a subtitle ` Testing`
</blockquote></details>

Done.

**Review by jonghoonkwon — APPROVED** [review]

**Review by jonghoonkwon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/84)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
