### PR TITLE
Move from MkDocs to Jekyll, so that we have "push to deploy"

### PR DESCRIPTION
**Pull request by AnotherKamila**
**Preview: https://anotherkamila.github.io/scion-tutorials/**

GitHub pages uses [Jekyll](https://jekyllrb.com) to render anything that has a _config.yml. Thus, we can use that to generate the docs.

This way we can make quick changes without faffing with recompilation. This way it works with the online editor, and we can't forget to compile.

I picked the theme that had more votes in the Slack poll, because I wanted to do that anyway, but now I can claim that you should fight it out among yourselves :P

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124)

### CODE REVIEW

**Review by mkowalski — CHANGES_REQUESTED** [review]
> Reviewed 373 of 373 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124)* status: all files reviewed, 2 unresolved discussions (waiting on @AnotherKamila, @FR4NK-W, and @matzf)

___
*[_config.yml, line 7 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtcoU4M1ZsPdEISZTDR:-LtcoU4M1ZsPdEISZTDS:bb2nw7f) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/_config.yml#L7)):*
> ```YAML
>   "SCIONLab":
>     - "https://scionlab.org/"
>   "SCION home page":
> ```

How about using upper camel case here?
___
*[_config.yml, line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-Ltcoal571LrLhjqxC9g:-Ltcoal571LrLhjqxC9h:bn3afw4) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/_config.yml#L9)):*
> ```YAML
>   "SCION home page":
>     - "https://scion-architecture.net/"
>   "NetSec github":
> ```

I'd change "NetSec" to something more obvious it's ETH's Network Security. Probably for a random dude in the internet "NetSec github" does not mean much :)
(also proposing upper camel case)

**Review by matzf — CHANGES_REQUESTED** [review]
Thank you! Added a bunch of minor comments & also some random things that I just saw when checking the new pages; the most important thing, I think is to simplify the navigation a bit by moving the "Configure end host" page back under the "Configuration" section, as this feels too complicated otherwise.

Otherwise, I have to admit the look of the theme is growing on me, I quite like it now :wink: The admonition boxes look nice too!

> Reviewed 372 of 373 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-:-LtfeVA5AWi6HcHfi65h:bv5xz30)* status: all files reviewed, 11 unresolved discussions (waiting on @AnotherKamila and @FR4NK-W)

___
*[.gitignore, line 12 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteTrWb4Ixja6vV6RJL:-LteTrWb4Ixja6vV6RJM:bmmu6a9) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/.gitignore#L12)):*
> ```ignore
> # jekyll-generated
> _site
> .jekyll-metadata
> ```

Broken newline?
___
*[content/advanced/setup_endhost.md, line 3 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteZvvB7-pN6IHpo-zp:-LteZvvB7-pN6IHpo-zq:b-cydkqu) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/advanced/setup_endhost.md#L3)):*
> ```Markdown
> ---
> title: Configuring SCION end host
> parent: Advanced
> ```

In contrast to the previous setup with mkdocs, the page map in this just-the-docs theme hides everything but the top categories and requires navigating to see what's in a toplevel category.
Therefore, I think we should avoid having more categories than really necessary. I would propose to remove the "Advanced" section and move this page back to "Configuration".
___
*[content/apps/access_camera.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfYyCNEacDNFk-7osD:-LtfYyCO87kcMJ3r1Wuz:bvxn9iy) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/apps/access_camera.md#L19)):*
> ```Markdown
> ```shell
> sudo apt install scion-apps-camerapp
> ```

(Unrelated to your changes, sorry)
Can you please:
- fix consistency with other pages: 
```
## Install

To install `camerapp`, run:

```

- remove the empty line in the shell snippet
___
*[content/apps/as_visualization/index.md, line 8 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-Ltf_pdfCuGyKNBiEIJn:-Ltf_pdfCuGyKNBiEIJo:b-5s4cdi) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/apps/as_visualization/index.md#L8)):*
> ```Markdown
> ---
> 
> # Webapp AS Visualization
> ```

Inconsistent title; I think "Webapp AS Visualization" would be nicer also for the nav title.

Also, wouldn't it make more sense to move the entire content of the "Webapp Overview" page here?
___
*[content/install/src.md, line 40 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfcsZ2CizN5zZROlhv:-LtfcsZ2CizN5zZROlhw:bnyge8i) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/install/src.md#L40)):*
> ```Markdown
> 
>         #!shell
>         sudo systemctl restart openvpn@client
> ```

This `#!shell` is supposed to define the language for the syntax highlighting -- instead it's now displayed verbatim. Yeah for compatibility in markdown parser :unamused: 
Can you try to figure out if there is a different mechanism, or just remove it? (Note: the tricky part is that, at least in py-markdown, fenced code blocks cannot be used as part of a list item...).
___
*[content/install/src.md, line 54 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfdgVa3nTqAc9l8XMH:-LtfdgVb3cL5RmamVNkG:b-yg8qha) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/install/src.md#L54)):*
> ```Markdown
> 
> {% include alert type="note" content="
> The configuration installed with the `scionlab-config` script as used in the [packaged installation](../install/pkg.md#configuration), is *not* directly compatible
> ```

Could you please remove the comma after the link
___
*[content/index.md, line 43 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteXBib0_XITFQ3bZIT:-LteXBib0_XITFQ3bZIU:bii2dcv) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/20060fedf7fbba421da93edf04daf1df20596430/content/index.md#L43)):*
> ```Markdown
> SCION is designed to interoperate with the existing networking infrastructure. Deployment of SCION can utilize existing internal routing and forwarding infrastructure of an AS, and only require installation or upgrade of a few border routers. A SCION-IP-Gateway (SIG) in the local infrastructure allows legacy end hosts and applications to be unaware of SCION.
> 
> #### References
> ```

The titles on this level look kind of shit, and it doesn't make sense that they're in the table of content. Can this be tweaked easily? Otherwise, I'd just drop the titles and make them bold text instead.
___
*[content/index.md, line 43 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteYDdH40KfQDQWGMMz:-LteYDdH40KfQDQWGMN-:bha5tcw) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/20060fedf7fbba421da93edf04daf1df20596430/content/index.md#L43)):*
> ```Markdown
> SCION is designed to interoperate with the existing networking infrastructure. Deployment of SCION can utilize existing internal routing and forwarding infrastructure of an AS, and only require installation or upgrade of a few border routers. A SCION-IP-Gateway (SIG) in the local infrastructure allows legacy end hosts and applications to be unaware of SCION.
> 
> #### References
> ```

Or actually, we could move this "references" down, just before the contacts, that would help I think.

The other titles on this level still look bad though.
___
*[content/apps/as_visualization/webapp.md, line 95 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfatGg51nTu-YYDnd-:-LtfatGh7fJK7HiC-ZEm:b-mbxc8l) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/apps/as_visualization/webapp.md#L95)):*
> ```Markdown
> * [Webapp SCIONLab Apps Visualization](../as_visualization/webapp_apps.md)
> * [Webapp Development Tips](../as_visualization/webapp_development.md)
> * [Verifying the installation](../config/check.md)
> ```

With the updated navigation with table of content, I think we should drop these related links (for all three of the webapp pages).

**Review by chaehni — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124)* status: all files reviewed, 12 unresolved discussions (waiting on @AnotherKamila and @FR4NK-W)

___
*[content/faq/troubleshooting.md, line 116 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtjRKg0D4BaDHKt6PNp:-LtjRKg24pgRYIabHawY:b-z2iluj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/faq/troubleshooting.md#L116)):*
> ```Markdown
> ## Getting help
> 
> If your stuck, don't hesitate to [get in contact](../index.md#contact)
> ```

This link seems to be broken in this updated version.

**Review by AnotherKamila — COMMENTED** [review]
@matzf thanks, I'm glad! Going to look at your suggestions now.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-:-LuWx1eqEg-MOnLJLtOO:b8su8a7)* status: 371 of 373 files reviewed, 12 unresolved discussions (waiting on @chaehni, @FR4NK-W, @matzf, and @mkowalski)

___
*[.gitignore, line 12 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteTrWb4Ixja6vV6RJL:-LuWx9uCDRV50-qDj-Tr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/.gitignore#L12)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Broken newline?
</blockquote></details>

Done.
___
*[_config.yml, line 7 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtcoU4M1ZsPdEISZTDR:-LuWwd2kClx5_wo1V7G-:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/_config.yml#L7)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

How about using upper camel case here?
</blockquote></details>

Done.
___
*[_config.yml, line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-Ltcoal571LrLhjqxC9g:-LuWwn560as3JCcCIBic:b4it1q1) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/_config.yml#L9)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

I'd change "NetSec" to something more obvious it's ETH's Network Security. Probably for a random dude in the internet "NetSec github" does not mean much :)
(also proposing upper camel case)
</blockquote></details>

Changed it to just "Our GitHub" because "ETH Network Security Group GitHub" felt way too verbose :D
___
*[content/advanced/setup_endhost.md, line 3 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteZvvB7-pN6IHpo-zp:-LuX4eql35P_eYkWUYNx:b-8qz70) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/advanced/setup_endhost.md#L3)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

In contrast to the previous setup with mkdocs, the page map in this just-the-docs theme hides everything but the top categories and requires navigating to see what's in a toplevel category.
Therefore, I think we should avoid having more categories than really necessary. I would propose to remove the "Advanced" section and move this page back to "Configuration".
</blockquote></details>

Done, and +1 to the general "we should avoid having more categories than really necessary" statement.
___
*[content/apps/access_camera.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfYyCNEacDNFk-7osD:-LuX5VoN4p0WDqWoPXUV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/apps/access_camera.md#L19)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

(Unrelated to your changes, sorry)
Can you please:
- fix consistency with other pages: 
```
## Install

To install `camerapp`, run:

```

- remove the empty line in the shell snippet
</blockquote></details>

Done.
___
*[content/apps/as_visualization/index.md, line 8 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-Ltf_pdfCuGyKNBiEIJn:-LuX5aht8Bvqtsvy7iSj:b2kwbxy) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/apps/as_visualization/index.md#L8)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Inconsistent title; I think "Webapp AS Visualization" would be nicer also for the nav title.

Also, wouldn't it make more sense to move the entire content of the "Webapp Overview" page here?
</blockquote></details>

Changed the title.

I think it makes sense to have these "index" pages be just a short overview with the table of contents for the sub-pages. Therefore, I moved the "Webapp Overview" page to a separate page, since it's long. If you disagree, we can discuss.
___
*[content/faq/troubleshooting.md, line 116 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtjRKg0D4BaDHKt6PNp:-LuXI5zxAJcZbogLxOxk:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/faq/troubleshooting.md#L116)):*
<details><summary><i>Previously, chaehni (chaehni) wrote…</i></summary><blockquote>

This link seems to be broken in this updated version.
</blockquote></details>

Done.
___
*[content/install/src.md, line 40 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfcsZ2CizN5zZROlhv:-LuXIdbxA6u0V5OIfsu1:b-85mpxj) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/install/src.md#L40)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This `#!shell` is supposed to define the language for the syntax highlighting -- instead it's now displayed verbatim. Yeah for compatibility in markdown parser :unamused: 
Can you try to figure out if there is a different mechanism, or just remove it? (Note: the tricky part is that, at least in py-markdown, fenced code blocks cannot be used as part of a list item...).
</blockquote></details>

Done. Fenced code blocks in a list item work here.
___
*[content/install/src.md, line 54 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfdgVa3nTqAc9l8XMH:-LuXIoGm25dPtBnvrdFq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/install/src.md#L54)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Could you please remove the comma after the link
</blockquote></details>

Done.
___
*[content/index.md, line 43 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteXBib0_XITFQ3bZIT:-LuWx_Tj0q_dwBCgdZfv:buxigsm) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/20060fedf7fbba421da93edf04daf1df20596430/content/index.md#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The titles on this level look kind of shit, and it doesn't make sense that they're in the table of content. Can this be tweaked easily? Otherwise, I'd just drop the titles and make them bold text instead.
</blockquote></details>

I have set the TOC to go only up to level 3 globally for the whole site.

I am not sure how to change the CSS -- it still looks shit :D I made it not upper case and bold, have a look at the updated page.
___
*[content/index.md, line 43 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LteYDdH40KfQDQWGMMz:-LuX3G9L-J9TPCF7QPXZ:b-otemmh) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/20060fedf7fbba421da93edf04daf1df20596430/content/index.md#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Or actually, we could move this "references" down, just before the contacts, that would help I think.

The other titles on this level still look bad though.
</blockquote></details>

I think this page may want to be re-thought anyway, so I'm not going to do this now. If you want to, go ahead, otherwise I'll ignore it for a while and maybe get back to it one day. At least I fixed the CSS :D
___
*[content/apps/as_visualization/webapp.md, line 95 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-LtfatGg51nTu-YYDnd-:-LuXGyM42A5VG6rv6pzm:b-5xcp2x) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2b195215418c25c586968214c551798a6a0022da/content/apps/as_visualization/webapp.md#L95)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

With the updated navigation with table of content, I think we should drop these related links (for all three of the webapp pages).
</blockquote></details>

Done. Kept the links to apps on the "Webapp Apps" page, as they seemed useful.

**Comment by AnotherKamila** [comment]
@matzf, @mkowalski, @chaehni ping? The changes you requested are done.

Can we merge this?

**Comment by mkowalski** [comment]
OK from my side

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-:-LulRzAQ3QrGyoDZIJcg:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @chaehni, @FR4NK-W, and @mkowalski)

**Review by chaehni — COMMENTED** [review]
:LGTM:  

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/124#-:-Lulo54k2k0t0WZo13AD:bh4lfo1)* status: all files reviewed, 2 unresolved discussions (waiting on @FR4NK-W and @mkowalski)

**Review by mkowalski — APPROVED** [review]

**Pull request merged**
