### PR TITLE
Update join_infrastructure.md

### PR DESCRIPTION
**Pull request by matzf**
Add link to sign up google form
Add reference to PCEngines supplied by us
Adjust wording analogous to scionlab.org main page

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)

### CODE REVIEW

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2f7K6sE5dMVLzLy1:-MJa2f7K6sE5dMVLzLy2:bik6cgs) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
> ```
> PCEngine
> ```

--> PCEngines

Does it really matter what type of box it is?

**Review by cmeury — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2qKV2zfT8OnYYQYe:-MJa2qKV2zfT8OnYYQYf:b1a8i39) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
> ```Markdown
> 
> 1. Tell us that you're interested in joining the SCIONLab infrastructure. Either fill in [this form](https://forms.gle/eZSfKhxnky2bwgFfA) or directly [get in contact with us](../../#contact).
> 2. Once the node(s) are ready on your side, create a `scionlab` user with full `sudo` rights and access for the SCIONLab team. In cases where we provide a PCEngine machine, this will have been prepared and you only have to plug it in.
> ```

Maybe mention that they will still have to ensure a proper networking setup, like a fixed IP, firewall exceptions?

**Comment by cmeury** [comment]
___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2f7K6sE5dMVLzLy1:-MJa3BEuAVcTEqTZ0Ilk:bn99xqv) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> PCEngine
> ```

--> PCEngines

Does it really matter what type of box it is?
</blockquote></details>

Also, is PC Engine a commonly known term? Might be better to use "small form-factor, low power server boxes" or similar?

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-:-MJa3oHT6g-BsaFB5MUL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cmeury, @FR4NK-W, and @juagargi)

___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2f7K6sE5dMVLzLy1:-MJa5UGO06Pa30vsCvkB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Also, is PC Engine a commonly known term? Might be better to use "small form-factor, low power server boxes" or similar? 
</blockquote></details>

Done.
___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2qKV2zfT8OnYYQYe:-MJa5Vtd2AO_c-eI5Iog:bgxofwr) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Maybe mention that they will still have to ensure a proper networking setup, like a fixed IP, firewall exceptions?
</blockquote></details>

Done, but kept it generic. Does that seem ok?

**Review by cmeury — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W, @juagargi, and @matzf)

___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2qKV2zfT8OnYYQYe:-MJa7HcLBeAnatqHEQMQ:bfe3ova) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Done, but kept it generic. Does that seem ok?
</blockquote></details>

Seems okay, just a typo in `willl`.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cmeury, @FR4NK-W, and @juagargi)

___
*[content/faq/join_infrastructure.md, line 19 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170#-MJa2qKV2zfT8OnYYQYe:-MJa8PzA-ML15gmNPtAM:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/9dbd36d2e57d9c7d32e4bafa7fc14af4f4f26b5e/content/faq/join_infrastructure.md#L19)):*
<details><summary><i>Previously, cmeury (Cedric Meury) wrote…</i></summary><blockquote>

Seems okay, just a typo in `willl`.
</blockquote></details>

Done.

**Review by cmeury — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/170)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
