### PR TITLE
New upgrade process

### PR DESCRIPTION
**Pull request by juagargi**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108)

### CODE REVIEW

**Review by mkowalski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[content/scion_tricks/updating_scion.md, line 67 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108#-LoztCzC0y3v3cvL-4Si:-LoztCzC0y3v3cvL-4Sj:b-bcc5ws) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/3ae6afb5b2da898a914966950b1c12667fde267b/content/scion_tricks/updating_scion.md#L67)):*
> ```Markdown
> ## Developers
> 
> As a developer, you probably don't need or want systemd to run and manage the SCION services for you. Stop it by running `sudo systemctl stop scionlab.target` and continue using `supervisord` as before.
> ```

I'd mention also `systemctl disable scionlab.target` here, otherwise after reboot all the stuff will be started as service again

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @juagargi)

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @mkowalski)

___
*[content/scion_tricks/updating_scion.md, line 67 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108#-LoztCzC0y3v3cvL-4Si:-Lp--DRy6Yugc_AmRH5A:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/3ae6afb5b2da898a914966950b1c12667fde267b/content/scion_tricks/updating_scion.md#L67)):*
<details><summary><i>Previously, mkowalski (Mateusz Kowalski) wrote…</i></summary><blockquote>

I'd mention also `systemctl disable scionlab.target` here, otherwise after reboot all the stuff will be started as service again
</blockquote></details>

Done.

**Review by mkowalski — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108)* status: 4 of 5 files reviewed, all discussions resolved

**Review by mkowalski — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/108)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
