### PR TITLE
Resolving SCION names

### PR DESCRIPTION
**Pull request by FR4NK-W**
Using rains over SCION

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/92)

### CODE REVIEW

**Review by juagargi — COMMENTED** [review]
There are many files modified under `docs`. Did you try to run `mkdocs build` from the venv that we just have in master? We have extended the README to also include instructions for this, so we all run the same `mkdocs` from now on.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/92#-:-L_8gOUf3mLRyY5Lu0DS:b-ru9caj)* status: 0 of 37 files reviewed, all discussions resolved (waiting on @juagargi)

**Review by FR4NK-W — COMMENTED** [review]
Yes I used the venv.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/92#-:-L_CpB4P3MwU04n_kjUq:b8b8ai)* status: 0 of 37 files reviewed, all discussions resolved

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/92#-:-L_CpWKk8bmKrm6nHUTV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/92#-:-L_IOazO3swyBV5g_GD6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
