### PR TITLE
Add BitTorrent over SCION doc

### PR DESCRIPTION
**Pull request by martenwallewein**
Hey All,

it would be great if we could add an entry to the SCIONLab documentation for our BitTorrent over SCION app. At the moment its feature set is not that impressive, but it's under active development and we have a lot of features on the roadmap. For newer versions of BitTorrent over SCION, I would keep the documentation site up-to-date with further PRs.

I would appreciate any feedback or comments.

Cheers!

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
Thank you, it's great to see more stuff here!
Why does this project not have a catchy name though? :wink: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-:-MxKSSz22jh9YzNeqG9h:b9baysy)* status: all files reviewed, 4 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[content/apps/bittorrent.md, line 17 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-MxKVP0Q7TYESh0Zn9fi:-MxKVP0Q7TYESh0Zn9fj:bfqlxwb) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5b94a58265791f8be9f205629eb7dd6b43dee0bc/content/apps/bittorrent.md#L17)):*
> ```Markdown
> go install github.com/netsys-lab/bittorrent-over-scion@v1.0.1
> ```
> For build instructions see [readme](https://github.com/netsys-lab/bittorrent-over-scion/readme.md) for details. You may have to ensure that your PATH variable is setup properly to run installed go binaries: `export PATH="${GOPATH}/bin:${PATH}"`
> ```

The `PATH` setting is not necessary for the examples below with where the executable is directly located (`./bitttorrent-over-scion`).
I'd skip this and assume readers are shell-literate.
___
*[content/apps/bittorrent.md, line 21 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-MxKHoHhD_pktAiWsNNf:-MxKHoHhD_pktAiWsNNg:bvxjid) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5b94a58265791f8be9f205629eb7dd6b43dee0bc/content/apps/bittorrent.md#L21)):*
> ```Markdown
> ## Usage
> 
> The general usage of bat is: `bittorrent-over-scion [flags]`.
> ```

`bat` ?
___
*[content/apps/bittorrent.md, line 35 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-MxKHzYY1rhuok3d0FLo:-MxKHzYZ5lAsPCvq9QYy:b-l2onj0) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5b94a58265791f8be9f205629eb7dd6b43dee0bc/content/apps/bittorrent.md#L35)):*
> ```Markdown
> | -logLevel | Specifies the loglevel, can be `DEBUG`,`INFO`,`WARN`,`ERROR`                                              
> 
> At the moment, peers can be either seeders (providing a file) or leechers (requesting a file). 
> ```

Please clean up trailing whitespace
___
*[content/apps/bittorrent.md, line 46 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-MxKQQ4t4wQAiDDwHO-u:-MxKQQ4t4wQAiDDwHO-v:b-i3nq94) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5b94a58265791f8be9f205629eb7dd6b43dee0bc/content/apps/bittorrent.md#L46)):*
> ```Markdown
> The following command runs BitTorrent as a leecher:
> ```sh
> ./bittorrent-over-scion -inPath='sample.torrent' -outPath='sample.file' -peer="19-ffaa:1:000,[127.0.0.1]:46000" -seed=false -local="19-ffaa:1:111,[127.0.0.1]:43000" 
> ```

Maybe use the commandline (peer address, torrent file name) for the demo torrent from below, to make it even  easier to try it out.

Maybe add an obvious placeholder for the `-local` flag -- I overlooked it and the tool doesn't complain if the address is bogus. Even better would be to get rid of this parameter, like the other scion demo apps.
___
*[content/apps/bittorrent.md, line 51 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-MxKR99k5Vfn5nYsofhV:-MxKR99k5Vfn5nYsofhW:bqkilhm) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5b94a58265791f8be9f205629eb7dd6b43dee0bc/content/apps/bittorrent.md#L51)):*
> ```Markdown
> ## Example torrents
> 
> We provide a [demo torrent](https://github.com/netsys-lab/bittorrent-over-scion/tree/master/demo) seeding a zip file of SCION videos under the following SCION address: `19-ffaa:1:c3f,[141.44.25.148]:43000`. To run a leecher and download this file, the respective torrent file needs to be downloaded before starting BitTorrent over SCION with he target SCION address. 
> ```

I tried this, unfortunately without success:
```
matfrei@metapod:~$ ./bittorrent-over-scion -inPath='sample.torrent' -outPath='sample.file' -peer="19-ffaa:1:c3f,[141.44.25.148]:43000" -seed=false -local=17-ffaa:1:c45,[129.132.85.120]:43000
INFO[0000] Input sample.torrent, Output sample.file, Peer 19-ffaa:1:c3f,[141.44.25.148]:43000, seed false, file
INFO[0000] Starting download for scion-videos.zip
2022/03/04 15:58:59 connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
ERRO[0005] timeout: no recent network activity
ERRO[0005] Could not handshake with 19-ffaa:1:c3f,[141.44.25.148]:43000-0. Disconnecting
```

Maybe the peer crashed? The first few tries the error message wasn't timeout but `buffer to small expected="2725" actual="1452"`.

**Comment by martenwallewein** [comment]
Hey Matthias, thanks for the feedback, I will tackle this asap and will think about a catchy name, maybe there is something cool.

I think I've fixed the "buffer to small" and the "timeout" problems, they were on the remote side. Will let you know when the rest is done.

**Comment by martenwallewein** [comment]
Hey ho! I've addressed your feedback in the latest commit. I'm not sure how I can resolve the individual remarks if this is intended :)

It would be cool if you could run it again, so that we can ensure that it works now.

As catchy name, the only thing that comes to my mind is bscion as short version of bittorrent over scion. :thinking:

**Review by matzf — APPROVED** [review]
:lgtm:

Ran the updated version again (now just copy-pasting the command line from "Run a leecher") and works! :tada: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-:-MxiNsax2JMjfgbHp33T:bs9f4gd)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[content/apps/bittorrent.md, line 46 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/189#-MxKQQ4t4wQAiDDwHO-u:-MxiNOsk6RfJCUq65jQQ:b-4cj3s9) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5b94a58265791f8be9f205629eb7dd6b43dee0bc/content/apps/bittorrent.md#L46)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Maybe use the commandline (peer address, torrent file name) for the demo torrent from below, to make it even  easier to try it out.

Maybe add an obvious placeholder for the `-local` flag -- I overlooked it and the tool doesn't complain if the address is bogus. Even better would be to get rid of this parameter, like the other scion demo apps.
</blockquote></details>

Excellent :+1:

**Pull request merged**
