### PR TITLE
 Adapt docs for SCIONLab update

### LINKED ISSUE #139: Adapt docs for SCIONLab update
* look for beacon-server/path-server/certificate server and mention certificate server instead
* describe changed usage of scion-apps

### PR DESCRIPTION
**Pull request by matzf**
* Update changed usage of applications
* Add section about common usage of applications (hostnames, environment variables)
* Adapt statements about control services to monolithic control server
* Update section on end host setup (actually got simpler due to using TCP)

Closes #139

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)

### CODE REVIEW

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[index.md, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140#-M2c1QFY2_kJHt434rlQ:-M2c1QF_6oo8-y3NRD00:b-r1xeeq) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/55c1f7daa473798dba0d858a19c887531fef01cd/index.md#L72)):*
> ```
> perform the process
> ```
The process? Which one. Was unclear already before

Maybe ->
'each AS hosts the infrastructure services that provide paths and certificate inforamtion and perform control plane updates such propagating beacons.'

**Review by FR4NK-W — COMMENTED** [review]
Nice

> Reviewed 10 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140#-:-M2cRugS-TzfATxDAA-k:bb70w76)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[index.md, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140#-M2c1QFY2_kJHt434rlQ:-M2cieLrDUJ2HX-reo2S:b3jw8b3) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/55c1f7daa473798dba0d858a19c887531fef01cd/index.md#L72)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> perform the process
> ```
The process? Which one. Was unclear already before

Maybe ->
'each AS hosts the infrastructure services that provide paths and certificate inforamtion and perform control plane updates such propagating beacons.'
</blockquote></details>

Good point. I noticed that what you proposed was almost identical to the paragraph immediately before. I've just merged the two paragraphs. How does that sound now?

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @matzf)

___
*[index.md, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140#-M2c1QFY2_kJHt434rlQ:-M2ckGKx9NrDqdwpFRDi:bsu0smq) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/55c1f7daa473798dba0d858a19c887531fef01cd/index.md#L72)):*
Better :thumbsup: 
>should traverse

must traverse

>is described

describes

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[index.md, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140#-M2c1QFY2_kJHt434rlQ:-M2cmSWeENENCSkMEE2Q:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/55c1f7daa473798dba0d858a19c887531fef01cd/index.md#L72)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Better :thumbsup: 
>should traverse

must traverse

>is described

describes
</blockquote></details>

Done.

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[index.md, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/140#-M2c1QFY2_kJHt434rlQ:-M2cmuY9-VZ_occ3hjkY:b-cshv2l) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/55c1f7daa473798dba0d858a19c887531fef01cd/index.md#L72)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Best :tada:

**Pull request merged**
