### PR TITLE
Small grammar fixes and rewording

### PR DESCRIPTION
**Pull request by CounterPillow**
Reword some sentences to read more naturally and also adjust the grammar a bit here and there.

Also, looks like there aren't any conventions on line wrapping, some lines appear to be statically wrapped, others are dynamically wrapped (or written on incredibly wide monitors.) Any opinions on which one should be preferred?

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132)

### CODE REVIEW

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @CounterPillow)

___
*[content/config/create_as.md, line 11 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132#-LwYp56n12BvBL3z_T_Y:-LwYp56n12BvBL3z_T_Z:b-1xul7k) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2fdc7daaf50025f596c42dfd9faffe22e0196f2c/content/config/create_as.md#L11)):*
> ```
> log in to
> ```
I think `login on` is fine.
___
*[content/install/src.md, line 9 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132#-LwYpaMtB2zuVGJQRn6t:-LwYpaMtB2zuVGJQRn6u:b6gtt4m) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2fdc7daaf50025f596c42dfd9faffe22e0196f2c/content/install/src.md#L9)):*
> ```
> If you're planning on making modifications
> ```
If you are planning to make modifications
___
*[content/install/vm.md, line 54 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132#-LwYq4vi-ULO6dAFmV6j:-LwYq4vi-ULO6dAFmV6k:b-378ghy) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/2fdc7daaf50025f596c42dfd9faffe22e0196f2c/content/install/vm.md#L54)):*
> ```
> allows you to move data both ways
> ```
enables moving data both ways.

**Comment by FR4NK-W** [comment]
Thank you for your PR.
Can you please rebase and apply the small changes?
Then we can merge it.

**Comment by CounterPillow** [comment]
Done.

**Comment by CounterPillow** [comment]
Done.

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/132)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
