### PR TITLE
Loosen requirements for infrastructure nodes

### PR DESCRIPTION
**Pull request by matzf**
Fewer ports, less strict wording.

Removed ports:
- monitoring: was used for 2SMS (maybe?); obsolete, monitoring will use a push model
- "management": 9100: that's just 2SMS-monitoring again
- OpenVPN: not a requirement for infrastructure nodes -- not even for attachment points!

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/105)

### CODE REVIEW

**Review by mkowalski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/105)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W, @juagargi, @matzf, and @mkowalski)

___
*[content/general_scion_configuration/join_infrastructure.md, line 17 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/105#-Li8KzbaBJDBI4ftcEen:-Li8KzbaBJDBI4ftcEeo:b7w3wzh) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/082b5d86a6ce226f3031096826de549d9ed625d2/content/general_scion_configuration/join_infrastructure.md#L17)):*
> ```Markdown
> - The following ports need to be accessible:
>     - For each configured SCION inter-domain connection one UDP port for SCION inter-domain traffic, preferrably in the 50000~50010 range.<br>
>       Preferrably, these ports should be open for any source IP, as this simplifies changes the SCIONLab topology. However, we can provide the specific allowed source IP for each port if necessary.<br>
> ```

"as this simplifies changes in the SCIONLab topology" or "as this simplifies changing the SCIONLab topology"

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/105)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W, @juagargi, and @matzf)

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/105)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi and @matzf)

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/105#-:-Lj1AC11CRu6QsxBGGMI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Pull request merged**
