### PR TITLE
SIGCOMM user AS health check

### PR DESCRIPTION
**Pull request by juagargi**
Tell the users from the SIGCOMM workshop to already check their ASes via the webapp health check.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)

### CODE REVIEW

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mlegner)

**Review by mlegner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[content/sigcomm/preparation.md, line 23 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-ME2V5sZ1crAcf4lz46K:-ME2V5s_8KySsQlJcZ5V:b-o64e3s) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/faca3e8c04f2a8fd2474e942eaf47e2f0619258f/content/sigcomm/preparation.md#L23)):*
> ```Markdown
>    * Install SCIONLab's webapp with `sudo apt-get install scion-apps-webapp`.
>    * Start the daemon with `sudo systemctl start scion-webapp.service`. The SCIONLab Webapp should be running now under port 8000 of the virtual machine. 
>    * In your host machine, outside of the virtual machine, open a browser and navigate to [http://localhost:8000/](http://localhost:8000/). Click on the health tab of the top bar. Every test should be green. If not, you can report the problem to us. Be sure to mention you will be part of the SIGCOMM Workshop when you [contact us](https://docs.scionlab.org/#contact).
> ```

They could also contact us directly in the conference's Slack channel.

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: all files reviewed, 1 unresolved discussion (waiting on @mlegner)

___
*[content/sigcomm/preparation.md, line 23 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-ME2V5sZ1crAcf4lz46K:-ME2ZE9T54VE0SqGSgZ8:b4c9lyr) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/faca3e8c04f2a8fd2474e942eaf47e2f0619258f/content/sigcomm/preparation.md#L23)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

They could also contact us directly in the conference's Slack channel.
</blockquote></details>

:thumbsup:

**Review by mlegner — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-:-ME2_pMjE1_UR1mSroL8:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[content/sigcomm/preparation.md, line 23 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-ME2V5sZ1crAcf4lz46K:-ME2aAfEBJZRaN-ju1mx:b-mhccu9) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/faca3e8c04f2a8fd2474e942eaf47e2f0619258f/content/sigcomm/preparation.md#L23)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Suggestion: "If not, you can report the problem to us via the tutorial's [slack channel](https://app.slack.com/client/T0107RGGMU6/C0186E0GY0G) or [contact us](https://docs.scionlab.org/#contact) by email. In the latter case, please mention that you will be part of the SIGCOMM workshop."

**Review by FR4NK-W — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[content/sigcomm/preparation.md, line 23 at r3](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-ME7bxM122XThxP9sXxU:-ME7bxM39OOPPdfXNB2X:bljqiyn) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/78a3f208c0aa37329390385ccf6b67439e421aa1/content/sigcomm/preparation.md#L23)):*
> ```
> https://app.slack.com/client/T0107RGGMU6/C0186E0GY0G
> ```

Are you sure that is the correct link? This redirects me to the default sign in page https://app.slack.com/signin , not the workspace like https://ethznetsec.slack.com/ does.

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[content/sigcomm/preparation.md, line 23 at r3](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-ME7bxM122XThxP9sXxU:-ME7qNaB6FQtYLIWmX9j:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/78a3f208c0aa37329390385ccf6b67439e421aa1/content/sigcomm/preparation.md#L23)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> https://app.slack.com/client/T0107RGGMU6/C0186E0GY0G
> ```

Are you sure that is the correct link? This redirects me to the default sign in page https://app.slack.com/signin , not the workspace like https://ethznetsec.slack.com/ does.
</blockquote></details>

Done.

**Review by juagargi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

**Review by mlegner — APPROVED** [review]
Everything :lgtm:.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163#-:-MENFiHG-fUmlyDcYXZ9:b-xkxy06)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/163)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
