### PR TITLE
Join infrastructure

### PR DESCRIPTION
**Pull request by juagargi**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78)

### CODE REVIEW

**Review by jonghoonkwon — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[content/general_scion_configuration/join_infrastructure.md, line 42 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78#-LTSkTLk7Nj5gDzgD8nk:-LTSkTLl5FJcIXl58WUA:b5fw5l5) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/6b72b13b48ce7613e12d57fd548ceac15bcc3ed9/content/general_scion_configuration/join_infrastructure.md#L42)):*
> ```Markdown
> - Check the requirements. If possible, follow the recommendations.
> - Get in contact with us. Send us an email to <scionlab-admins@sympa.ethz.ch> telling us you want to join the infrastructure.
> - Once the node(s) are ready, you will have to grant the SCIONLab admins `ssh` access to the machine via a key.
> ```

I'd like to emphasize here that we recommand to create an account name of `scion`.

**Review by jonghoonkwon — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78#-:-LTSlNR48VqJa5juUWkR:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78)* status: all files reviewed, 1 unresolved discussion (waiting on @jonghoonkwon)

___
*[content/general_scion_configuration/join_infrastructure.md, line 42 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78#-LTSkTLk7Nj5gDzgD8nk:-LTSrc2a3AcGZL8bE6Kr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/6b72b13b48ce7613e12d57fd548ceac15bcc3ed9/content/general_scion_configuration/join_infrastructure.md#L42)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

I'd like to emphasize here that we recommand to create an account name of `scion`.
</blockquote></details>

Done.

**Review by jonghoonkwon — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78)* status: all files reviewed, 1 unresolved discussion (waiting on @jonghoonkwon)

**Review by jonghoonkwon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/78)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
