### PR TITLE
faq/join_infra: Firewall configuration update

### PR DESCRIPTION
**Pull request by AnotherKamila**
1. Is this split better? (I think it makes sense, because this way we can send
   the direct link to just that info to network operators when prodding them to
   fix the firewall.)
2. What did I forget in outgoing connections?

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131)

### CODE REVIEW

**Review by mkowalski — COMMENTED** [review]
(1) Yes, that makes sense
(2) The outgoing is very tricky. You need lots of stuff like e.g. access to the package repository for the OS, package repository for the SCIONLab packages and tons of different things. If you are really trying to build a matrix for running SCIONLab from inside an air-gapped zone, you are entering a path with lots of bumps. I personally would stick with the version "outgoing access to the Internet has to be provided" as this will save you lots of time and nerves.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131#-:-LwNqap_7x1Cf5lVxcm7:b-eg7kkj)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @matzf and @mkowalski)

**Review by mkowalski — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131)* status: all files reviewed, 2 unresolved discussions (waiting on @AnotherKamila)

___
*[content/faq/as_connectivity.md, line 2 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131#-LwNvZvGEi8AVP4OiKRw:-LwNvZvGEi8AVP4OiKRx:b-aul14k) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5a891072e09fab98c9fb539e99e00745e468eaaa/content/faq/as_connectivity.md#L2)):*
> ```Markdown
> ---
> title: SCION AS connectivity requirements
> ```

Maybe rather "_SCIONLab_ AS connectivity requirements" to not give the wrong impression that this is applies to SCION in general.
___
*[content/faq/as_connectivity.md, line 39 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131#-LwNwoyh8HowYpen1i4Q:-LwNwoyh8HowYpen1i4R:b-5l8nd9) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5a891072e09fab98c9fb539e99e00745e468eaaa/content/faq/as_connectivity.md#L39)):*
> ```Markdown
> | UDP            | 30000--35000 | machines in the same SCION AS | SCION intra-AS connectivity |
> | TCP            | 80, 443      | 0.0.0.0/0     | Software updates, monitoring |
> | UDP            | 51820        | 82.130.64.0/18<br> 129.132.0.0/16<br> 195.176.96.0/19<br> 192.33.87.0/24<br> 192.33.88.0/23<br> 192.33.91.0/24<br> 192.33.92.0/24<br> 192.33.93.0/24<br> 192.33.94.0/23<br> 192.33.96.0/21<br> 192.33.104.0/22<br> 192.33.108.0/23<br> 192.33.110.0/24 | Administrative access for monitoring |
> ```

Maybe mention that this is a wireguard VPN.

**Review by AnotherKamila — COMMENTED** [review]
Re (2), unfortunately you are right, but according to Jonghoo, this is the problem with the KREONET people. Thus, if we're going to have a more restricted firewall there, I'd rather explicitly document our actual requirements than have a "special case" for them. 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131#-:-LwO-ZffAQcK74h0VEHB:beq48x3)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[content/faq/as_connectivity.md, line 2 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131#-LwNvZvGEi8AVP4OiKRw:-LwO-C4o5Th4nXa3Q25n:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5a891072e09fab98c9fb539e99e00745e468eaaa/content/faq/as_connectivity.md#L2)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Maybe rather "_SCIONLab_ AS connectivity requirements" to not give the wrong impression that this is applies to SCION in general.
</blockquote></details>

Done.
___
*[content/faq/as_connectivity.md, line 39 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131#-LwNwoyh8HowYpen1i4Q:-LwO-FAu7cEjt1ovmzof:b-rkvfy3) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/5a891072e09fab98c9fb539e99e00745e468eaaa/content/faq/as_connectivity.md#L39)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Maybe mention that this is a wireguard VPN.
</blockquote></details>

Honestly, I'm not 100% sure if I want to be mentioning it, as the same people that make "all outgoing" difficult might be concerned with allowing a VPN :D Of course they would figure it out if they looked, but it is possible that they will not look :D

**Review by mkowalski — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/131)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

**Pull request merged**
