### PR TITLE
Clarify what SCIONLab is (and is not)

### PR DESCRIPTION
**Pull request by tzaeschke**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202)

### CODE REVIEW

**Review by JordiSubira — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202)* status: 0 of 1 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`index.md` line 13 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-O0UWcKkDZJwpJevy_kp:-O0UWcKkDZJwpJevy_kq:b1u1y8f) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/4b09de6f7692a1947b64469b6181669316716e54/index.md#L13)):*
> ```Markdown
> It also provides a list of interesting projects that are using the SCION infrastructure for communication.
> 
> **Note**: SCIONLab is a *testbed* network for SCION with *limited performance* and *intended for developers* only. If you want to 
> ```

primarly? I don't think we have to exclude also users completely, as long as they know what they are doing...



_Code quote:_
```Markdown
only
```
___
*[`index.md` line 14 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-O0UWwmMEvLPMMsJF0O_:-O0UWwmMEvLPMMsJF0Oa:bbh2spe) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/4b09de6f7692a1947b64469b6181669316716e54/index.md#L14)):*
> ```Markdown
> 
> **Note**: SCIONLab is a *testbed* network for SCION with *limited performance* and *intended for developers* only. If you want to 
> connect to the normal public SCION network, please refer to the [official website](https://scion.org) or [follow the instruction here](https://docs.scion.org). 
> ```

The problem with this is that the docs is too broad. It also may convey the idea that one will find how to connect as end user to a SCION ISP, which I don't think it is straightforward,



_Code quote:_
```Markdown
normal public SCION network,
```

**Review by tzaeschke — COMMENTED** [review]
Is that better?

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-:-O0hLBACA4ya2bKHcivX:b-58tlfd)* status: 0 of 1 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`index.md` line 13 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-O0UWcKkDZJwpJevy_kp:-O0hL-oz48kOqmA5s_vg:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/4b09de6f7692a1947b64469b6181669316716e54/index.md#L13)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

primarly? I don't think we have to exclude also users completely, as long as they know what they are doing...
</blockquote></details>

Done.
___
*[`index.md` line 14 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-O0UWwmMEvLPMMsJF0O_:-O0hL6hd9ddEArP1rjcw:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/4b09de6f7692a1947b64469b6181669316716e54/index.md#L14)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

The problem with this is that the docs is too broad. It also may convey the idea that one will find how to connect as end user to a SCION ISP, which I don't think it is straightforward,
</blockquote></details>

Done.

**Review by JordiSubira — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-:-O0hPpkXCocw5nucxujf:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Comment by tzaeschke** [comment]
Hi @JordiSubira After talking to Francois I changed the first sentence to `SCIONLab is a *testbed* network for SCION with *limited performance* intended for *development and experimentation*.`. The idea is that SCIONLab is not only intended for developers but also researchers and others. 
What do you think?

 If you like it, can you merge the PR? I do not have the rights.

**Review by FR4NK-W — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/202#-:-O0hwo3x8555TngjOxxS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
