### PR TITLE
Instructions for 'make install' and IP updates

### PR DESCRIPTION
**Pull request by mwfarb**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103)

### CODE REVIEW

**Review by juagargi — CHANGES_REQUESTED** [review]
Just some comments

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-:-LhGXoFV8vBMKHdg1n8v:b-rtt6en)* status: all files reviewed, 2 unresolved discussions (waiting on @mwfarb)

___
*[content/as_visualization/webapp.md, line 12 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-LhGX4pv9E4a0ZxJ8QjV:-LhGX4pv9E4a0ZxJ8QjW:b-o1ntug) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/389720d85bf0acae994541caaf7e898d22c3c673/content/as_visualization/webapp.md#L12)):*
> ```Markdown
> git clone https://github.com/netsec-ethz/scion-apps.git
> cd scion-apps
> ```
> ```

I would clarify here that they can run `./deps.sh` and `make`
___
*[content/sample_projects/access_camera.md, line 17 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-LhGXTsJ5gQGSjdTOC1g:-LhGXTsJ5gQGSjdTOC1h:b-834nj5) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/389720d85bf0acae994541caaf7e898d22c3c673/content/sample_projects/access_camera.md#L17)):*
> ```Markdown
> 
> !!! note
>     If you are running SCION in a VM this app is already installed.
> ```

is that still true with our VMs?

**Review by mwfarb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103)* status: all files reviewed, 2 unresolved discussions (waiting on @juagargi and @mwfarb)

___
*[content/sample_projects/access_camera.md, line 17 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-LhGXTsJ5gQGSjdTOC1g:-LhGnEix4-yOvhyMCsX6:b7lbakt) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/389720d85bf0acae994541caaf7e898d22c3c673/content/sample_projects/access_camera.md#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

is that still true with our VMs?
</blockquote></details>

Good question. Was it ever true? Did our updates ever install anything from scion-apps?

**Review by juagargi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103)* status: all files reviewed, 2 unresolved discussions (waiting on @mwfarb)

___
*[content/sample_projects/access_camera.md, line 17 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-LhGXTsJ5gQGSjdTOC1g:-LhKlzoaCMPGvtedZnam:b-s9a2ig) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/389720d85bf0acae994541caaf7e898d22c3c673/content/sample_projects/access_camera.md#L17)):*
<details><summary><i>Previously, mwfarb (mwfarb) wrote…</i></summary><blockquote>

Good question. Was it ever true? Did our updates ever install anything from scion-apps?
</blockquote></details>

Not really. The `scion-apps` repository was running independent of the `netsec-scion` one totally, and our update script never took care of it.

**Review by mwfarb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[content/as_visualization/webapp.md, line 12 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-LhGX4pv9E4a0ZxJ8QjV:-LhMSvL0CLV4r_HFGTn1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/389720d85bf0acae994541caaf7e898d22c3c673/content/as_visualization/webapp.md#L12)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

I would clarify here that they can run `./deps.sh` and `make`
</blockquote></details>

Done.
___
*[content/sample_projects/access_camera.md, line 17 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-LhGXTsJ5gQGSjdTOC1g:-LhMTEq-DWbrF1t2aRKk:byjipcm) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/389720d85bf0acae994541caaf7e898d22c3c673/content/sample_projects/access_camera.md#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Not really. The `scion-apps` repository was running independent of the `netsec-scion` one totally, and our update script never took care of it.
</blockquote></details>

Ok, I just removed this then for all. We can add it back when the packages are pre-built.

**Review by juagargi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/103#-:-LhQZPYdAsuAmupI5A79:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
