### PR TITLE
Updates for SCIONLab update

### PR DESCRIPTION
**Pull request by matzf**
- Replace `scmp echo` with `scion ping`
- Use `journalctl` instead of log files
- Update to flat config file structure (`/etc/scion/*` instead of
  `/etc/scion/gen/ISDx/ASy/brX-Y-Z/*`) and corresponding service names
- Update endhost setup to flat config
- Describe how to inspect metrics, not only logs for connectivity checks
- Remove (outdated) webapp developer information. Most of this is already covered by the README.
- Add warning about not-yet-updated webapp and android app

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173)

### CODE REVIEW

**Comment by marcfrei** [comment]
___
*[content/apps/remote_sig.md, line 73 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMhsHk7EHP0GY6tENC:-MMMhsHl4RDxjFBOazTV:b-jurymf) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/apps/remote_sig.md#L73)):*
> ```Markdown
> Start the SIG process on both hosts, by executing:
> ```shell
> sudo -u scion sig --config=/etc/scion/sig.toml
> ```

The usage string in scionproto/scion documents the sig config flag still with one dash instead of with a double dash. Should this be changed in scionproto?

**Comment by marcfrei** [comment]
___
*[content/config/check.md, line 104 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMpdoLBRkPhLbrUhnH:-MMMpdoLBRkPhLbrUhnI:b-1q6leb) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/config/check.md#L104)):*
> ```Markdown
> 
> 
> *   Alternatively, you can check the same information in metrics of the control service, exposed by default on localhost, port 30454.
> ```

Will we keep using 30454 as the monitoring port and not 30452 as in https://github.com/scionproto/scion/wiki/Default-port-ranges ?

**Comment by marcfrei** [comment]
___
*[content/config/check.md, line 127 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMrabM9VGMGi9esbxY:-MMMrabM9VGMGi9esbxZ:b-eg8lo3) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/config/check.md#L127)):*
> ```Markdown
> where a SCION address has the form `ISD-AS,IP`. An example of pinging a host in the attachment point AS in Korea would look as follows:
> 
>     $ scion ping 20-ffaa:0:1404,0.0.0.0
> ```

The output in scionproto looks currently more like

```
Resolved local address:
  127.0.0.1
Using path:
  Hops: [1-ff00:0:112 1>2 1-ff00:0:110 1>41 1-ff00:0:111] MTU: 1280 NextHop: 127.0.0.25:31020

PING 1-ff00:0:111,0.0.0.0:0 pld=0B scion_pkt=112B
120 bytes from 1-ff00:0:111,0.0.0.0: scmp_seq=0 time=1.104ms
...
```

Close enough, I guess.

**Review by marcfrei — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @marcfrei)

___
*[content/apps/remote_sig.md, line 73 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMhsHk7EHP0GY6tENC:-MMPJbAt-dolsgjzNc3a:bdpg5kc) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/apps/remote_sig.md#L73)):*
Oh, great catch! :eyes:

> Should this be changed in scionproto?

I expect it will be changed eventually. Some people at Anapaya are apparently rewriting the SIG and I guess this change will be included.
___
*[content/config/check.md, line 104 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMpdoLBRkPhLbrUhnH:-MMPKhnRD3Be3cfmMj9n:b-3y55xn) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/config/check.md#L104)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Will we keep using 30454 as the monitoring port and not 30452 as in https://github.com/scionproto/scion/wiki/Default-port-ranges ?
</blockquote></details>

Another good catch :eyes:.
So it was [changed](https://github.com/scionproto/scion/wiki/Default-port-ranges/_compare/250b73786a359a504f669abd8469e0aaf13602d8...cee16ac869ad860a2af23a6bcec23ccffebc59ee) again :roll_eyes:

We could change this when we clean up the bigger problems we had with clashing port assignments. I've added a note to the [issue](https://github.com/netsec-ethz/scionlab/issues/318).

Perhaps best  would be not to give a specific port here but read it from the config file. It just makes for a very messy oneliner. What do you think?

```
curl -sfS `sed -n 's/prometheus = "\?\([^"]*\)"\?/\1/p' /etc/scion/cs-1.toml`/metrics | grep registered_beacons_total
```
___
*[content/config/check.md, line 127 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMrabM9VGMGi9esbxY:-MMPYcEw3iSCROx9rd2k:bkbi4qu) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/config/check.md#L127)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

The output in scionproto looks currently more like

```
Resolved local address:
  127.0.0.1
Using path:
  Hops: [1-ff00:0:112 1>2 1-ff00:0:110 1>41 1-ff00:0:111] MTU: 1280 NextHop: 127.0.0.25:31020

PING 1-ff00:0:111,0.0.0.0:0 pld=0B scion_pkt=112B
120 bytes from 1-ff00:0:111,0.0.0.0: scmp_seq=0 time=1.104ms
...
```

Close enough, I guess.
</blockquote></details>

OK. Doctored a bit with the output :)

**Comment by marcfrei** [comment]
___
*[content/config/check.md, line 104 at r1](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173#-MMMpdoLBRkPhLbrUhnH:-MMPfGv-0U_mACKtiym0:b-y7b7zh) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/94a0c0d98c0c3849a2bbcaa004f28b3b8df1785c/content/config/check.md#L104)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Another good catch :eyes:.
So it was [changed](https://github.com/scionproto/scion/wiki/Default-port-ranges/_compare/250b73786a359a504f669abd8469e0aaf13602d8...cee16ac869ad860a2af23a6bcec23ccffebc59ee) again :roll_eyes:

We could change this when we clean up the bigger problems we had with clashing port assignments. I've added a note to the [issue](https://github.com/netsec-ethz/scionlab/issues/318).

Perhaps best  would be not to give a specific port here but read it from the config file. It just makes for a very messy oneliner. What do you think?

```
curl -sfS `sed -n 's/prometheus = "\?\([^"]*\)"\?/\1/p' /etc/scion/cs-1.toml`/metrics | grep registered_beacons_total
```
</blockquote></details>

Yes the expression looks quite wild. On the other hand it works and we are here in copy-paste territory anyways.

The only other question would be, whether we should do the same for the border router metrics query above: `curl -sfS localhost:30442/metrics`

**Comment by marcfrei** [comment]
:lgtm:

**Review by marcfrei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @marcfrei)

**Review by marcfrei — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/173)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
