### PR TITLE
WIP: Add first raw SCION Browser doc

### PR DESCRIPTION
**Pull request by martenwallewein**
Hey all, 

this is a first draft of our documentation for the SCION Browser extension. For now it's in a first, unpolished state, but it would be great to start discussing and improving this documentation.

Cheers,
Marten

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/190)

### CODE REVIEW

**Comment by JordiSubira** [comment]
As discussed before, we could add some usage information for adding host to the SCION forwarded list and also for the current geofencing (whitelisting) feature.

**Comment by martenwallewein** [comment]
Good point, didn't find the time to do so yet. I gave you permissions for my repo, please feel free to add all of your points and update the PR :)

**Review by FR4NK-W — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/190#-:-NfC30M2-_4hGPik-fXm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/190)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
