### PR TITLE
User APs

### PR DESCRIPTION
**Pull request by fl99kl**
These changes belong to the User AP feature (https://github.com/netsec-ethz/scionlab/pull/306)

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182)* status: 0 of 1 files reviewed, 7 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[content/config/create_as.md, line 42 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCvS1mCEW-aao7zn6U:-MaCvS1mCEW-aao7zn6V:b-9liqf5) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L42)):*
> ```Markdown
> *   Installation Type: select the way you have installed or will install SCION. Please refer to [Installation/Pick an Option](../install/index.html).
> 
> *   Make this AS a publicly available Attachment Point: select this if you want your Host to be an Attachment Point
> ```

Please make this a separate "section" by splitting it of with a `-----` line.
___
*[content/config/create_as.md, line 42 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCxSF57ISg5QmdjWQh:-MaCxSF57ISg5QmdjWQi:b-8rb4f) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L42)):*
> ```
> your Host to to be an Attachment Point
> ```

your *User AS* to be ...
___
*[content/config/create_as.md, line 42 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCzDSO1j7M2kShIbPY:-MaCzDSO1j7M2kShIbPZ:b2n1mhf) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L42)):*
> ```Markdown
> *   Installation Type: select the way you have installed or will install SCION. Please refer to [Installation/Pick an Option](../install/index.html).
> 
> *   Make this AS a publicly available Attachment Point: select this if you want your Host to be an Attachment Point
> ```

The readability of this page was not great from the start; a first simple step might be to mark all the option names bold (e.g. `**Installation Type**:`). Could you please apply this to the existing docs and your new additions? 
___
*[content/config/create_as.md, line 43 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCwrVy9prVZLLHz6E7:-MaCwrVy9prVZLLHz6E8:bvb3mcr) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L43)):*
> ```Markdown
> 
> *   Make this AS a publicly available Attachment Point: select this if you want your Host to be an Attachment Point
>         As an User Attachment Point you are a provider AS, which means that other ASes can use a connection to you to become part of the Scionlab infrastructure. To be shown in the list of available Attachment Points your host will have to run the scionlab-config daemon, in order to refresh its configuration whenever other users create or modify links to your AS
> ```

This paragraph is over-indented (in markdown); use only 4 spaces to indent.

Please add an empty line before this line to create a linebreak in the rendered text.
___
*[content/config/create_as.md, line 43 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCxlP6AUaqnyC2c6nh:-MaCxlP6AUaqnyC2c6ni:b-dc2cos) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L43)):*
> ```
> As an User Attachment Point you are a provider AS which means that other ASes can use a connection to you to become part of the Scionlab infrastructure
> ```

Other users will be able to select your AS as an Attachment Point for their ASes.
As Attachment Point, your AS serves as a transit provider, connecting these child ASes to each other and to the rest of the SCIONLab network.


Line break (empty line) after this sentence.
___
*[content/config/create_as.md, line 45 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaD0n7S50j_Q3iqMEhW:-MaD0n7S50j_Q3iqMEhX:b-9xgn2f) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L45)):*
> ```
>         To be shown in the list of available Attachment Points your host will have to run the scionlab-config daemon, in order to refresh its configuration whenever other users create or modify links to your AS
>         You can do so by starting the associated service file. This requires you to have queried the config for your AS at least once.
>         Afterwards you can run `systemctl start scionlab-config.service` to continuously get the latest config.
> ```

Split first sentence & reverse, e.g.
Your host needs to refresh its configuration whenever [...]. For this, it will need to run the scionlab-config daemon. Only Attachment Points that are running this scionlab-config daemon will be listed as available options to other users.

Then:
When setting up your Attachment Point host, first follow the instructions to install and configure your host as usual.
Then start the `scionlab-config` daemon with `systemctl enable --now scionlab-config.service`.

(note: we should suggest enable not start to keep this running after a restart).

> ```
> Alternatively you can run `scionlab-config --daemon`.
> ```
Drop this.
___
*[content/config/create_as.md, line 47 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCwXLw4GSsraji-ubJ:-MaCwXLw4GSsraji-ubK:b-let9fi) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L47)):*
> ```Markdown
>         Afterwards you can run `systemctl start scionlab-config.service` to continuously get the latest config. Alternatively you can run `scionlab-config --daemon`.
> 
> *   Public IP: enter your Public IP Address that should be used for connections to child ASes. This field is required when the `Make this AS a publicly available Attachment Point` field is selected.
> ```

Indent these points to make it a bit clearer that they are only applicable when the User AP option is enabled.

**Review by fl99kl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182)* status: 0 of 1 files reviewed, 7 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[content/config/create_as.md, line 42 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCvS1mCEW-aao7zn6U:-MaTclpd-aC4jqXSdcKY:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L42)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Please make this a separate "section" by splitting it of with a `-----` line.
</blockquote></details>

Done.
___
*[content/config/create_as.md, line 42 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCxSF57ISg5QmdjWQh:-MaTdDqABpxyNAywsLWl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L42)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
> your Host to to be an Attachment Point
> ```

your *User AS* to be ...
</blockquote></details>

Done.
___
*[content/config/create_as.md, line 42 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCzDSO1j7M2kShIbPY:-MaTdH7f-lZsJctoLOG2:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L42)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The readability of this page was not great from the start; a first simple step might be to mark all the option names bold (e.g. `**Installation Type**:`). Could you please apply this to the existing docs and your new additions? 
</blockquote></details>

Done.
___
*[content/config/create_as.md, line 43 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCwrVy9prVZLLHz6E7:-MaTetvP6RMQVkRO8oCc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This paragraph is over-indented (in markdown); use only 4 spaces to indent.

Please add an empty line before this line to create a linebreak in the rendered text.
</blockquote></details>

Done.
___
*[content/config/create_as.md, line 43 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCxlP6AUaqnyC2c6nh:-MaTfTni7ODwNZZJmRGT:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L43)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
> As an User Attachment Point you are a provider AS which means that other ASes can use a connection to you to become part of the Scionlab infrastructure
> ```

Other users will be able to select your AS as an Attachment Point for their ASes.
As Attachment Point, your AS serves as a transit provider, connecting these child ASes to each other and to the rest of the SCIONLab network.


Line break (empty line) after this sentence.
</blockquote></details>

Done.
___
*[content/config/create_as.md, line 45 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaD0n7S50j_Q3iqMEhW:-MaThG5LCiOl_DjtkdNP:b-zf8we5) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L45)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
>         To be shown in the list of available Attachment Points your host will have to run the scionlab-config daemon, in order to refresh its configuration whenever other users create or modify links to your AS
>         You can do so by starting the associated service file. This requires you to have queried the config for your AS at least once.
>         Afterwards you can run `systemctl start scionlab-config.service` to continuously get the latest config.
> ```

Split first sentence & reverse, e.g.
Your host needs to refresh its configuration whenever [...]. For this, it will need to run the scionlab-config daemon. Only Attachment Points that are running this scionlab-config daemon will be listed as available options to other users.

Then:
When setting up your Attachment Point host, first follow the instructions to install and configure your host as usual.
Then start the `scionlab-config` daemon with `systemctl enable --now scionlab-config.service`.

(note: we should suggest enable not start to keep this running after a restart).

> ```
> Alternatively you can run `scionlab-config --daemon`.
> ```
Drop this.
</blockquote></details>

Done, used enable.
___
*[content/config/create_as.md, line 47 at r2](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182#-MaCwXLw4GSsraji-ubJ:-MaThN0MEEoXq5kHxJ87:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-tutorials/blob/266dbc1708d9809c5a814c1220c2e1517704455a/content/config/create_as.md#L47)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Indent these points to make it a bit clearer that they are only applicable when the User AP option is enabled.
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-tutorials/182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fl99kl)

**Pull request merged**
